## PAIR PROGRAMMING PANDAS I 
---

**EJERCICIO 1**

¿Qué diferencia hay entre una Serie y un DataFrame?

> La diferencia principal es la estructura de datos, siendo en la serie una dimensión y en el dataframe tiene dos. 

---

**EJERCICIO 2**

Momento de trabajar con Series. Contestad a las siguientes preguntas:
- Crea dos listas:
    - Una que se llame "valores" que tenga 7 números aleatorios.
    - Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.
- A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.
- A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.
- Crea una Serie con el diccionario creado en el punto anterior.
- ¿Qué forma tiene esta última Serie?
- ¿Qué tipo de datos tiene?
- ¿Qué tamaño tiene?
- ¿Cuáles son los índices de la Serie?
- ¿Y los values?
- Extraed el valor para el índice "lunes"
- Extraed el valor para el índice "lunes", "martes" y "miércoles".
- Extraed el valor para el índice "lunes" y "domingo".

In [108]:
import pandas as pd
import numpy as np

In [109]:

lista_valores = [3, 13, 7, 45, 9, 6, 22]
lista_indices= ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']

In [110]:
# Creamos una serie con las dos listas, utilizando una de ellas para los índices y la otra para los values.

Serie1= pd.Series(lista_valores, index = ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo'])
Serie1


lunes         3
martes       13
miercoles     7
jueves       45
viernes       9
sabado        6
domingo      22
dtype: int64

In [111]:
# Definimos una función para crear un diccionario de la serie anterior, para poder iterar por las listas de la serie, 
# utilizamos el método zip.

diccionario_series= list(zip(lista_indices, lista_valores))

def crear_dicc_serie(lista):
    dicc_vacio = {}

    for i,e in diccionario_series:
        dicc_vacio[i] = e

    return dicc_vacio
        
        
        


In [112]:
crear_dicc_serie(diccionario_series)

{'lunes': 3,
 'martes': 13,
 'miercoles': 7,
 'jueves': 45,
 'viernes': 9,
 'sabado': 6,
 'domingo': 22}

In [113]:
# Creamos una serie con el diccionario anterior utilizando el pd.Series y poniendo entre paréntesis el diccionario que queremos convertir.

Serie2 = pd.Series(crear_dicc_serie(diccionario_series))
Serie2

lunes         3
martes       13
miercoles     7
jueves       45
viernes       9
sabado        6
domingo      22
dtype: int64

In [114]:
# Forma

Serie2.shape

(7,)

In [115]:
# Tipo

Serie2.dtype

dtype('int64')

In [116]:
# Tamaño/nº elementos

Serie2.size

7

In [117]:
# Comprobamos los índices de la serie

Serie2.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

In [118]:
# Comprobamos los values de la serie

Serie2.values

array([ 3, 13,  7, 45,  9,  6, 22])

In [119]:
# Extraemos el valor para el índice "lunes"

#Utilizamos el método values indicando el índice del que queremos obtener el valor
Serie2.values[0]

# LLamando al índice de la key nos da el value
Serie2[0]




3

In [120]:
# Extraemos el valor para el índice "lunes", "martes" y "miércoles" con el método value y el rango de los índices que queremos 
# entre corchetes

Serie2.values[0:3]

array([ 3, 13,  7])

In [121]:
# Extraemos el valor para el índice "lunes" y "domingo" con el método values e indicando entre dos corchetes el primer y último índice,
# separándolo con coma en vez con dos puntos como para el rango.

Serie2.values[[0 , -1]]

array([ 3, 22])

---

**EJERCICIO 3**

Es el turno de los DataFrames

- Cread un array de dos dimensiones con 4 filas y 3 columnas.
- Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
- Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:

df = pd.read_csv("medallas.csv", index_col=["País"])

📌 NOTA Para evitar problemas guardar el archivo medallas.csv a la misma altura (en la misma carpeta) que el jupyter donde estamos trabajando.

- Usando el loc extraed todas las columnas de la fila.
- Usando el loc extraed todas las columnas de China e Irán.
- Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
- Usando el iloc extraed la información de la India. Devolved todas las columnas.
- Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
- Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".
- Contestad a las siguientes preguntas:
    - ¿Qué país consiguió más de 200 medallas de oro?
    - ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
    - ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
    - Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.
    - Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [123]:
# Creamos un array 2D utilizando el metodo ramdon.randint con los números aleatorios entre 1 y 50,  
# y le pasamos el número de filas y columnas entre paréntesis.

array1 = np.random.randint(1,50, (4,3))
array1

array([[22,  7, 20],
       [ 7,  4,  8],
       [44, 32, 18],
       [41, 45, 21]])

In [124]:
# Convertimos el array en un DataFrame, asignando el nombre de las columnas

medallas = pd.DataFrame(array1, columns = ["España", "Francia", "Italia"])
medallas

España  Francia  Italia
0      22        7      20
1       7        4       8
2      44       32      18
3      41       45      21

In [125]:
# Descargamos el archivo con el código facilitado

df = pd.read_csv("medallas.csv", index_col=["País"])

In [126]:
df.head()

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827
Irán                    4   179    181     197
Kazajistán              5   155    158     224

In [127]:
df.loc[:, :]

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [128]:
df.loc[["China", "Irán"], : "Bronce"]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [129]:
df.loc[["China", "Irán"], "Oro":"Bronce"]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

In [130]:
df.iloc[5, :]

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

In [131]:
# La posición del los índices de python es impar, pero la posición de los índices que se muestran en el 
# dataframe son pares. Start 1 en japón, 10 para la última fila y saltos de 2.

df.iloc[1:10:2, :]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

In [132]:
df.iloc[1:10:2, 1:4]

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

In [133]:
 # ¿Qué país consiguió más de 200 medallas de oro?
 
df.loc[df.Oro > 200]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [134]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?


df.loc[(df.Oro > 200) | (df.Bronce > 700)]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [135]:
# Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.

#df.drop(df.columns[0], axis= 1)

df = df.drop(['Unnamed: 0'],axis =1)
df

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

In [137]:
# Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las 
# medallas obtenidas por cada país.

df['Resultado'] = (df['Oro']+df['Plata']+df['Bronce'])
df

Oro  Plata  Bronce  Resultado
País                                           
China            1473    994     720       3187
Japón            1032   1037     985       3054
Corea del Sur     745    663     827       2235
Irán              179    181     197        557
Kazajistán        155    158     224        537
India             154    202     315        671
Tailandia         132    175     278        585
Indonesia         112    131     240        483
China Taipéi       99    144     276        519
Corea del Norte    91    120     235        446

In [138]:
df.head(10)

Oro  Plata  Bronce  Resultado
País                                           
China            1473    994     720       3187
Japón            1032   1037     985       3054
Corea del Sur     745    663     827       2235
Irán              179    181     197        557
Kazajistán        155    158     224        537
India             154    202     315        671
Tailandia         132    175     278        585
Indonesia         112    131     240        483
China Taipéi       99    144     276        519
Corea del Norte    91    120     235        446