## PAIR PROGRAMMING NUMPY I
---

**EJERCICIO 1**

Cread tres arrays: de una, dos y tres dimensiones.

Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas en algunos casos.

📌 Nota

El array de 2 dimensiones debe ser de 2 filas y 3 columnas

El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [2]:
import numpy as np
import random

In [3]:
# Array de una dimensión

array_uni = np.array((1,1,1))
array_uni


array([1, 1, 1])

In [5]:
# Array bidimensional pasándole directamente los números con el método np.array.

array_bi = np.array([[5,2,13],[4,62,73]])
array_bi

array([[ 5,  2, 13],
       [ 4, 62, 73]])

In [6]:
lista1 = [3,5,7]
lista2 = [7,6,8]

In [23]:
# Array bidimensional pasándole las listas creadas en la celda anterior.

array_bi2 = np.array([lista1,lista2])
array_bi2

array([[3, 5, 7],
       [7, 6, 8]])

In [8]:
# Array tridimensional utilizando el método np.random.randint

array_tri = np.random.randint(1,100,(2,3,5))
array_tri


array([[[ 9,  1, 46, 60, 26],
        [10, 54, 69, 46, 65],
        [21, 79, 37, 16, 91]],

       [[59, 35,  3, 42, 85],
        [93, 89,  9, 26, 56],
        [66, 29, 13, 60, 83]]])

---

**EJERCICIO 2** 

Chequead las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [9]:

def propiedades_array(array):
    ```Función para comprobar las propiedades básicas de un array.
       Llamar a la función pasándole el parámetro de un array```
    array.shape
    array.size
    array.ndim
    array.dtype
    return f'La forma del array es {array.shape}, el numero de elementos es {array.size}, 
    las dimensiones son {array.ndim} y el tipo de dato contenido es {array.dtype}'




In [24]:
propiedades_array(array_uni)

'La forma del array es (3,), el numero de elementos es 3, las dimensiones son 1 y el tipo de dato contenido es int64'

In [11]:
propiedades_array(array_bi)

'La forma del array es (2, 3), el numero de elementos es 6, las dimensiones son 2 y el tipo de dato contenido es int64'

In [12]:
propiedades_array(array_tri)


'La forma del array es (2, 3, 5), el numero de elementos es 30, las dimensiones son 3 y el tipo de dato contenido es int64'

---

**EJERCICIO 3**
 
Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [13]:
# Matriz identidad con el método np.identity

array_id = np.identity(3)
array_id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

**EJERCICIO 4**
 
Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [14]:
array_tri

array([[[ 9,  1, 46, 60, 26],
        [10, 54, 69, 46, 65],
        [21, 79, 37, 16, 91]],

       [[59, 35,  3, 42, 85],
        [93, 89,  9, 26, 56],
        [66, 29, 13, 60, 83]]])

In [15]:
# Hacemos la copia del array_tri con el método np.ones_like

copia_array_unos = np.ones_like(array_tri)
copia_array_unos

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

---


**EJERCICIO 5**

Es el momento de hacer algunas operaciones entre arrays

¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

Dividid las dos matricess

In [16]:
# No podemos sumar el array bidimensional con la matriz de identidad ya que no tienen 
# las mismas propiedades (dimensiones, forma)

In [17]:
print(array_bi) 
print(array_id)

[[ 5  2 13]
 [ 4 62 73]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# Creamos un array nuevo a partir del array_bi introduciendo una lista con el valor 1. 

array_tri_2 = np.array([[5,2,13],[4,62,73],[1,1,1]])

In [26]:
# Sumamos
np.add(array_tri_2, array_id)

array([[ 6.,  2., 13.],
       [ 4., 63., 73.],
       [ 1.,  1.,  2.]])

In [27]:
# Multiplicammos
np.multiply(array_tri_2, array_id)

array([[ 5.,  0.,  0.],
       [ 0., 62.,  0.],
       [ 0.,  0.,  1.]])

In [28]:
# Dividimos
np.divide(array_id, array_tri_2)

array([[0.2       , 0.        , 0.        ],
       [0.        , 0.01612903, 0.        ],
       [0.        , 0.        , 1.        ]])