## PAIR PROGRAMMING NUMPY II
---

In [1]:
import numpy as np
import random 

**EJERCICIO 1**

Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
- El valor de la primera fila y la segunda columna.
- Los valores de la segunda fila y las dos primeras columnas.
- Extraed las filas pares (incluyendo la 0) y todas las columnas.
- Extraed los valores que sean mayores que 0.5.
- Extraed los valores menores que 0.2 o mayores que 0.5

In [2]:
# Creamos un array de valores tipo integers con el método ramdom.randint
array_2d = np.random.randint(0,20, (5,3))
array_2d

array([[12, 10, 19],
       [ 6, 19, 10],
       [ 5,  7,  4],
       [ 6,  7, 15],
       [ 2, 17,  4]])

In [3]:
# El valor de la primera fila y la segunda columna.

array_2d[0,1]

10

In [4]:
# Los valores de la segunda fila y las dos primeras columnas.

array_2d[1,:2]

array([ 6, 19])

In [5]:
# Extraed las filas pares (incluyendo la 0) y todas las columnas.

array_2d[0::2]

array([[12, 10, 19],
       [ 5,  7,  4],
       [ 2, 17,  4]])

In [6]:
# Extraed los valores que sean mayores que 0.5.

array_2d[array_2d > 0.5]

array([12, 10, 19,  6, 19, 10,  5,  7,  4,  6,  7, 15,  2, 17,  4])

In [7]:
# Extraed los valores menores que 0.2 o mayores que 0.5

array_2d[(array_2d < 0.2) | (array_2d > 0.5)]

array([12, 10, 19,  6, 19, 10,  5,  7,  4,  6,  7, 15,  2, 17,  4])

In [8]:
# Hacemos el ejercicio uno creando un array de valores tipo float con el método ramdom.rand

array_decimal = np.random.rand(5,3)
array_decimal

array([[0.49493538, 0.62974127, 0.57287077],
       [0.49130225, 0.25529102, 0.64336998],
       [0.20481675, 0.06355683, 0.52531031],
       [0.46260345, 0.32341308, 0.70807321],
       [0.28191082, 0.62664939, 0.47810917]])

In [9]:
array_decimal[0,1]

0.629741273930009

In [10]:
array_decimal[1,:2]

array([0.49130225, 0.25529102])

In [11]:
array_decimal[0::2]

array([[0.49493538, 0.62974127, 0.57287077],
       [0.20481675, 0.06355683, 0.52531031],
       [0.28191082, 0.62664939, 0.47810917]])

In [12]:
array_decimal[array_decimal > 0.5]

array([0.62974127, 0.57287077, 0.64336998, 0.52531031, 0.70807321,
       0.62664939])

In [13]:
array_decimal[(array_decimal < 0.2) | (array_decimal > 0.5)]

array([0.62974127, 0.57287077, 0.64336998, 0.06355683, 0.52531031,
       0.70807321, 0.62664939])

---

**EJERCICIO 2**

Cread dos array de tres dimensiones:
- El primero de 2 matrices, 5 filas y 3 columnas.
- El segundo de 3 matrices, 2 filas y 5 columnas.
- Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.
- Sumad los dos arrays. ¿Podéis? ¿Por qué?
- Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:
    - .reshape()
    - .transpose()
    
    Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [14]:
# Creamos el array de 2 matrices, 5 filas y 3 columnas

array_3d = np.random.rand(2,5,3)
array_3d

array([[[0.6057395 , 0.14886757, 0.45888219],
        [0.04055505, 0.4758217 , 0.21438178],
        [0.49758851, 0.21878025, 0.41141364],
        [0.50458413, 0.49837026, 0.4412849 ],
        [0.63587788, 0.09116866, 0.76412324]],

       [[0.61635949, 0.94690285, 0.65368822],
        [0.52718572, 0.31329497, 0.48281566],
        [0.19070509, 0.27563542, 0.29007822],
        [0.71213072, 0.91205708, 0.87756922],
        [0.31247038, 0.90180535, 0.0132278 ]]])

In [15]:
# El segundo de 3 matrices, 2 filas y 5 columnas

array2_3d= np.random.rand(3,5,2)
array2_3d

array([[[0.86197116, 0.40979041],
        [0.43740122, 0.29316054],
        [0.42181227, 0.77143172],
        [0.28422838, 0.1213745 ],
        [0.60717951, 0.83998237]],

       [[0.54608244, 0.21200874],
        [0.42749795, 0.69658878],
        [0.84847901, 0.09890141],
        [0.49895059, 0.27044072],
        [0.52719132, 0.59670251]],

       [[0.7416032 , 0.0760308 ],
        [0.75728095, 0.11569678],
        [0.98569154, 0.50683623],
        [0.35623486, 0.76257421],
        [0.4544456 , 0.46929593]]])

In [18]:
# Análisis exploratorio de los array con una función creada para ello

def propiedades_array(array):
    array.shape
    array.size
    array.ndim
    array.dtype
    return f'La forma del array es {array.shape}, el numero de elementos es {array.size}, las dimensiones son {array.ndim} y el tipo de dato contenido es {array.dtype}'


In [19]:
propiedades_array(array_3d)

'La forma del array es (2, 5, 3), el numero de elementos es 30, las dimensiones son 3 y el tipo de dato contenido es float64'

In [ ]:
propiedades_array(array2_3d)

'La forma del array es (3, 5, 2), el numero de elementos es 30, las dimensiones son 3 y el tipo de dato contenido es float64'

In [ ]:
np.add(array_3d, array2_3d) #No podemos sumarlo por tener formas diferentes.

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,5,2) 

In [ ]:
# Cambiamos la forma del segundo array, array2_3d, con el método transpose y lo guardamos en la 
# variable arraytrans, igualándolo a la forma del array_3d para poder sumarlos en la siguiente celda.

arraytrans= np.transpose(array2_3d, (2,1,0))
arraytrans

array([[[0.23507125, 0.45423736, 0.71914445],
        [0.50160988, 0.97648517, 0.51895234],
        [0.73595618, 0.12119883, 0.36712574],
        [0.2770729 , 0.3158952 , 0.57367003],
        [0.81977586, 0.2251486 , 0.70808563]],

       [[0.89796823, 0.95905481, 0.38371504],
        [0.27334711, 0.12978778, 0.85244976],
        [0.49505768, 0.6869492 , 0.73812282],
        [0.55736212, 0.76327337, 0.32444272],
        [0.39653569, 0.7217564 , 0.58849597]]])

In [ ]:
# Sumamos los dos arrays.

np.add(array_3d, arraytrans)

array([[[0.97329431, 0.97140151, 1.18680852],
        [0.61829027, 1.06522447, 1.17595373],
        [1.64558956, 0.8257412 , 0.97860088],
        [1.13904977, 0.75554344, 1.38460986],
        [1.04983196, 0.72665097, 0.963906  ]],

       [[1.05785114, 1.94410845, 0.66045052],
        [0.78692346, 0.14678149, 1.74171388],
        [1.42183759, 1.00810916, 1.28818433],
        [0.75386045, 1.3072462 , 0.48013092],
        [0.64989754, 1.57086887, 1.3133057 ]]])

In [ ]:
# Cambiamos la forma del array, array_3d, con el método reshape y lo guardamos en la variable 
# arraysha, igualándolo a la forma del array_3d para poder sumarlos en la siguiente celda.

arraysha= array_3d = np.reshape(array_3d, (3, 5, 2))
arraysha

array([[[0.24706445, 0.31298815],
        [0.37260427, 0.00373906],
        [0.20119273, 0.16589038],
        [0.58972437, 0.48373422],
        [0.0413657 , 0.87627672]],

       [[0.71506673, 0.99643391],
        [0.66632568, 0.33265652],
        [0.04971185, 0.65897798],
        [0.61309578, 0.26204148],
        [0.19182756, 0.54493866]],

       [[0.38013675, 0.70586496],
        [0.18309636, 0.40902662],
        [0.89492177, 0.0469691 ],
        [0.03687116, 0.98101362],
        [0.56306695, 0.26578889]]])

In [ ]:
# Sumamos

np.add(array2_3d, arraysha)

array([[[0.4821357 , 1.21095638],
        [0.87421415, 0.27708617],
        [0.93714891, 0.66094807],
        [0.86679728, 1.04109634],
        [0.86114156, 1.2728124 ]],

       [[1.16930409, 1.95548872],
        [1.64281085, 0.4624443 ],
        [0.17091067, 1.34592718],
        [0.92899098, 1.02531486],
        [0.41697616, 1.26669505]],

       [[1.09928119, 1.08958001],
        [0.70204869, 1.26147637],
        [1.26204751, 0.78509192],
        [0.61054119, 1.30545633],
        [1.27115258, 0.85428486]]])