## NUMPY III: Operaciones estadísticas y matemáticas
---

In [21]:
import numpy as np 
import random 

**EJERCICIO 1**

Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. 

Sobre el array creado anteriormente, extraed:

In [22]:
array = np.random.rand(2,3,5)
array = array.round(1)

In [23]:
array

array([[[0.6, 0.2, 0.4, 0.9, 0.1],
        [0. , 0.1, 0.7, 0.9, 0.8],
        [0.6, 0.7, 0.2, 0.8, 0.8]],

       [[0.5, 0.8, 0.5, 1. , 0.6],
        [0.5, 0.6, 0.5, 0.6, 0. ],
        [0.6, 0. , 0.7, 0.5, 0.9]]])

---

**EJERCICIO 2** 

Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [24]:
media = np.round(np.mean(array), decimals = 1)
media 

0.5

**EJERCICIO 3**  

Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [25]:
maximo = np.round(np.max(array), decimals = 1)
maximo

1.0

---

**EJERCICIO 4**

Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [26]:
minimo = np.round(np.min(array), decimals = 1)
minimo 

0.0

---

**EJERCICIO 5** 

Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.

Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

In [27]:
array2 = np.empty_like(array, dtype= str)
array2

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

Si el valor del array es igual que la media, se reemplaza por "A".


Si el valor del array es mayor que la media, se reemplaza por "B".


Si el valor del array es menor que la media, se reemplaza por "C".


Si el valor es igual que el máximo, se reemplaza por "D".


Si el valor es igual que el mínimo, se reemplaza por "E".

💡 Pista 💡 Tendréis que iterar por el array y cambiar los valores de la matriz vacía. Para eso tendremos que usar distintos condicionales.

In [28]:
array.shape

(2, 3, 5)

In [29]:
# Iteramos para sacar todos los posibles de un array tridimensional [0][1][2] en array.shape

for arr in range(array.shape[0]):
    for fila in range(array.shape[1]):
        for columna in range(array.shape[2]):
            if array[arr,fila, columna] == media:
                array2[arr, fila, columna] = "A"
            elif array[arr,fila, columna] > media:
                array2[arr, fila, columna] = "B"
            elif array[arr,fila, columna] < media:
                array2[arr, fila, columna] = "C"
            elif array[arr,fila, columna] == maximo:
                array2[arr, fila, columna] = "D"
            elif array[arr,fila, columna] == minimo:
                array2[arr, fila, columna] = "E"
print(array2)

[[['B' 'C' 'C' 'B' 'C']
  ['C' 'C' 'B' 'B' 'B']
  ['B' 'B' 'C' 'B' 'B']]

 [['A' 'B' 'A' 'B' 'B']
  ['A' 'B' 'A' 'B' 'C']
  ['B' 'C' 'B' 'A' 'B']]]


---

**EJERCICIO 6**

Estupendo, tenemos un array con strings. 

Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. 

Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.


En este caso:


Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1


Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2


Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.


Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [30]:
array2

array([[['B', 'C', 'C', 'B', 'C'],
        ['C', 'C', 'B', 'B', 'B'],
        ['B', 'B', 'C', 'B', 'B']],

       [['A', 'B', 'A', 'B', 'B'],
        ['A', 'B', 'A', 'B', 'C'],
        ['B', 'C', 'B', 'A', 'B']]], dtype='<U1')

In [31]:
# Creamos un array vacio de 30 elementos y una sola dimensión especificar el numero de elementos con np.empty

array_vacio = np.empty(30)
array_vacio

array([0.6, 0.2, 0.4, 0.9, 0.1, 0. , 0.1, 0.7, 0.9, 0.8, 0.6, 0.7, 0.2,
       0.8, 0.8, 0.5, 0.8, 0.5, 1. , 0.6, 0.5, 0.6, 0.5, 0.6, 0. , 0.6,
       0. , 0.7, 0.5, 0.9])

In [39]:
# Cambiamos la forma al array_vacio a uno unidimensional de 30, igual que el anterior
array30 = np.reshape(array2,(30)) 
array30

array(['B', 'C', 'C', 'B', 'C', 'C', 'C', 'B', 'B', 'B', 'B', 'B', 'C',
       'B', 'B', 'A', 'B', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'C', 'B',
       'C', 'B', 'A', 'B'], dtype='<U1')

In [36]:
# Iteramos por los indices del array30 (por los números en el rango de 0 a la longitud del array)
# Creamos las condiciones para que para cada indice sustituya las letras por los números indicados.

for i in range(len(array30)): 
    if array30[i] =='A' or  array30[i] == 'B': 
        array_vacio[i] = 1
    if array30[i] =='C' or array30[i] =='D':
        array_vacio[i] = 2
    if array30[i] =='E' :
        array_vacio[i] = 3

In [37]:
array_vacio

array([1., 2., 2., 1., 2., 2., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 1.])

In [38]:
# Cambiamos la forma del array a la forma original para que sea de tridimensional, con 2 matrices, 3 filas y 5 columnas.

array_final = np.reshape(array_vacio,(2,3,5))
array_final

array([[[1., 2., 2., 1., 2.],
        [2., 2., 1., 1., 1.],
        [1., 1., 2., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 2.],
        [1., 2., 1., 1., 1.]]])